name: Atriumn Development Pipeline

on:
  workflow_dispatch:
    inputs:
      phase:
        description: 'The pipeline phase to run (research, plan, implement, validate)'
        required: true
        type: string
      issue_number:
        description: 'The issue number'
        required: true
        type: string
      pr_number:
        description: 'The pull request number'
        required: true
        type: string
      head_sha:
        description: 'The SHA of the commit to run checks against'
        required: true
        type: string
      task_description:
        description: 'The task description for the AI'
        required: false
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write

jobs:
  run-phase:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Status Check: In Progress'
        id: create_check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const phase = '${{ inputs.phase }}';
            const phaseTitle = phase.charAt(0).toUpperCase() + phase.slice(1);
            const checkName = `Atriumn Phase: ${phaseTitle}`;

            const { data: check } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: checkName,
              head_sha: '${{ inputs.head_sha }}',
              status: 'in_progress',
              output: {
                title: `Running ${phaseTitle}`,
                summary: 'The AI agent is currently executing the ${phase} phase.'
              }
            });
            return check.id;

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: feature/issue-${{ inputs.issue_number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure output directories exist
        run: |
          mkdir -p thoughts/shared/{research,decisions,plans}/tmp

      - name: Load task-pack prompt for phase
        id: load_prompt
        run: |
          PROMPT_PATH=".atriumn/task-packs/${{ inputs.phase }}.md"
          if [[ ! -f "$PROMPT_PATH" ]]; then
            echo "Missing task-pack prompt: $PROMPT_PATH" >&2
            exit 1
          fi
          # Read and escape the prompt for JSON embedding
          PROMPT_CONTENT=$(cat "$PROMPT_PATH")
          echo "prompt<<EOF" >> $GITHUB_ENV
          echo "$PROMPT_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run Claude Code Agent
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          timeout_minutes: 40
          allowed_tools: "Read,Write,Edit,MultiEdit,Grep,Glob,LS,TodoWrite"
          direct_prompt: |
            ${{ env.prompt }}
            ---
            # Context variables:
            feature_ref = "feature/issue-${{ inputs.issue_number }}"
            issue_number = "${{ inputs.issue_number }}"
            repository = "${{ github.repository }}"
            task_description = "${{ inputs.task_description }}"
            phase = "${{ inputs.phase }}"

      - name: Commit & push artifacts
        run: |
          git config user.name "atriumn-bot"
          git config user.email "bot@atriumn.dev"
          git add thoughts/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "feat(${{ inputs.phase }}): AI-generated artifacts for issue #${{ inputs.issue_number }}"
            git push origin "feature/issue-${{ inputs.issue_number }}"
          fi
      
      - name: 'Update Status Check: Success'
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const phase = '${{ inputs.phase }}';
            const phaseTitle = phase.charAt(0).toUpperCase() + phase.slice(1);
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.create_check.outputs.result }},
              status: 'completed',
              conclusion: 'success',
              output: {
                title: `${phaseTitle} Phase Complete!`,
                summary: 'The AI agent successfully completed the ${phase} phase. The generated artifacts have been committed. Please review the changes in the PR and provide your approval to proceed to the next phase.'
              }
            });

      - name: 'Update Status Check: Failure'
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const phase = '${{ inputs.phase }}';
            const phaseTitle = phase.charAt(0).toUpperCase() + phase.slice(1);
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: ${{ steps.create_check.outputs.result }},
              status: 'completed',
              conclusion: 'failure',
              output: {
                title: `${phaseTitle} Phase Failed`,
                summary: 'The AI agent encountered an error during the ${phase} phase. Please check the workflow logs for details.'
              }
            });