name: Atriumn Development Pipeline

on:
  workflow_dispatch:
    inputs:
      phase:
        description: 'The pipeline phase to run (research, plan, implement, validate)'
        required: true
        type: string
      issue_number:
        description: 'The issue number'
        required: true
        type: string
      pr_number:
        description: 'The pull request number'
        required: true
        type: string
      head_sha:
        description: 'The SHA of the commit to run checks against'
        required: true
        type: string
      task_description:
        description: 'The task description for the AI'
        required: false
        type: string

permissions:
  contents: write
  issues: write
  pull-requests: write
  checks: write

jobs:
  run-phase:
    runs-on: ubuntu-latest
    steps:
      - uses: atriumn/atriumn-issue-driven-development@main
        with:
          phase: ${{ inputs.phase }}
          issue_number: ${{ inputs.issue_number }}
          pr_number: ${{ inputs.pr_number }}
          head_sha: ${{ inputs.head_sha }}
          task_description: ${{ inputs.task_description }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}