# curatefor.me specific configuration
repo_name: "curatefor.me"
base_branch: "develop"
thoughts_directory: "thoughts/"

validation:
  research_min_refs: 3
  implementation_test_commands:
    - "make test"
    - "make lint"
    - "make typecheck"
  pr_required_sections:
    - "Summary"
    - "Related Documents" 
    - "Testing"
    - "Changes Made"
    - "Verification"

notifications:
  slack_channel: "#dev-team"
  escalation_hours: 2

team:
  default_reviewers: ["@jeff-atriumn"]
  domain_experts:
    frontend: "@frontend-expert"
    backend: "@backend-expert"
    infrastructure: "@devops-lead"
  tech_lead: "@tech-lead"

branches:
  prefix: "feature/"
  naming: "issue-{number}-{title-slug}"
  cleanup_merged: true

workflow_customization:
  auto_proceed_default: false
  phase_timeouts:
    research_hours: 4
    planning_hours: 2
    implementation_hours: 24
  parallel_pipelines: 3

integration_settings:
  deployment_environments: ["staging", "production"]