# Copy this to your repo: .github/workflows/development-pipeline.yml
name: Development Pipeline

on:
  issue_comment:
    types: [created]

jobs:
  # Only trigger on pipeline-related comments in issues
  check-trigger:
    if: |
      github.event.issue &&
      (contains(github.event.comment.body, '@atriumn-pipeline start') ||
       contains(github.event.comment.body, '✅ Research Phase Complete') ||
       contains(github.event.comment.body, 'approve research') ||
       contains(github.event.comment.body, '✅ Planning Phase Complete') ||
       contains(github.event.comment.body, 'approve plan') ||
       contains(github.event.comment.body, '✅ Implementation Phase Complete') ||
       contains(github.event.comment.body, 'approve implementation'))
    runs-on: ubuntu-latest
    outputs:
      should_trigger: ${{ steps.check.outputs.should_trigger }}
    steps:
      - name: Check if should trigger pipeline
        id: check
        run: |
          echo "should_trigger=true" >> $GITHUB_OUTPUT
          echo "Triggering shared development pipeline"

  development-pipeline:
    needs: check-trigger
    if: needs.check-trigger.outputs.should_trigger == 'true'
    uses: atriumn/atriumn-shared-workflows/.github/workflows/development-pipeline.yml@main
    with:
      repo_name: ${{ github.repository }}
      issue_number: ${{ github.event.issue.number }}
    secrets:
      REPO_TOKEN: ${{ secrets.PIPELINE_TOKEN }}

# Configuration Instructions:
# 
# 1. Copy this file to your repository at: .github/workflows/development-pipeline.yml
# 
# 2. Update the repository name if different from github.repository
# 
# 3. Create a repository secret named PIPELINE_TOKEN:
#    - Go to Settings > Secrets and variables > Actions
#    - Create new repository secret: PIPELINE_TOKEN
#    - Value: Your GitHub Personal Access Token with repo permissions
# 
# 4. Optional: Create repo-specific config at .github/development-pipeline-config.yml:
#    repo_name: "your-repo-name"
#    base_branch: "main"  # or "develop", "master"
#    thoughts_directory: "thoughts/"  # or "docs/", "documentation/"
#    
#    validation:
#      research_min_refs: 3
#      implementation_test_commands:
#        - "npm test"
#        - "npm run lint"
#        - "npm run typecheck"
#    
#    team:
#      default_reviewers: ["@your-username"]
#    
#    notifications:
#      slack_channel: "#dev-team"
# 
# 5. Test the pipeline:
#    - Create an issue in your repository
#    - Comment: "@atriumn-pipeline start"
#    - The pipeline will create a branch and guide Claude through the process
# 
# 6. Pipeline modes:
#    - Human validation (default): "@atriumn-pipeline start"
#    - Fully automated: "@atriumn-pipeline start\nHuman validation: false"
#    - Custom base branch: "@atriumn-pipeline start\nBase branch: develop"