# GitHub App manifest for Atriumn Issue-Driven Development
name: Atriumn Issue-Driven Development
description: AI-powered development pipeline that turns GitHub issues into working code
url: https://github.com/atriumn/atriumn-issue-driven-development
hook_attributes:
  url: https://90a45654962b.ngrok-free.app/api/webhook
redirect_url: https://github.com/atriumn/atriumn-issue-driven-development

# Permissions required by the app
default_permissions:
  issues: read
  contents: read
  actions: write
  metadata: read

# Events the app subscribes to
default_events:
  - issue_comment

# Public app settings
public: false
request_oauth_on_install: false